spring:
  datasource:
      driver-class-name: oracle.jdbc.driver.OracleDriver
      url: jdbc:oracle:thin:@192.168.100.121:1521/lcdev
      username: train
      password: train
      hikari:
          schema: Train


